query getAllBookChapters($bookId: String!) {
    chapters (where: {
        book: {
            is: {
                id: {
                    equals: $bookId
                }
            }
        }
    }) {
        id
        name
        top {
            id
        }
    }
}
