query getChapter($chapterId: String!) {
    chapter (where: {
        id: $chapterId
    }) {
        id
        book {
            id
        }
        name
        type
        paragraphs {
            id
            content
            align
            firstLineIndent
        }
        nestedChapters {
            id
            name
        }
        top {
            id
            name
        }
        next {
            id
            name
        }
        prev {
            id
            name
        }
    }
}
